spring:
  datasource:
    url: jdbc:h2:mem:darlemlih;MODE=MySQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  flyway:
    enabled: false   # disable Flyway for H2 profile (fastest)
  mail:
    host: localhost
    port: 1025

server:
  port: 8080

app:
  base-url: http://localhost:8080

jwt:
  access-ttl-min: 15
  refresh-ttl-days: 7
