spring:
  datasource:
    url: jdbc:mysql://localhost:3306/darlemlih?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: dar
    password: lemlih
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  flyway:
    enabled: true
  mail:
    host: localhost
    port: 1025

server:
  port: 8080

app:
  base-url: http://localhost:8080

jwt:
  access-ttl-min: 15
  refresh-ttl-days: 7
